# Bag-of-words

In [32]:
%run -i "../util/util_simple_classifier.ipynb"
from sklearn.feature_extraction.text import CountVectorizer
import sys

In [33]:
(train_df, test_df) = load_train_test_dataset_pd()

Found cached dataset rotten_tomatoes (/home/zhenya/.cache/huggingface/datasets/rotten_tomatoes/default/1.0.0/40d411e45a6ce3484deed7cc15b82a53dad9a72aafd9f86f8f227134bec5ca46)
Found cached dataset rotten_tomatoes (/home/zhenya/.cache/huggingface/datasets/rotten_tomatoes/default/1.0.0/40d411e45a6ce3484deed7cc15b82a53dad9a72aafd9f86f8f227134bec5ca46)


In [82]:
vectorizer = CountVectorizer(max_df=0.4)
X = vectorizer.fit_transform(train_df["text"])
print(X)

  (0, 6568)	1
  (0, 2103)	1
  (0, 715)	1
  (0, 42)	1
  (0, 1277)	1
  (0, 5250)	1
  (0, 1604)	1
  (0, 3625)	1
  (0, 3401)	1
  (0, 4750)	1
  (0, 7335)	1
  (0, 2704)	1
  (0, 3471)	1
  (0, 7873)	1
  (0, 486)	1
  (0, 6759)	1
  (0, 4260)	1
  (0, 1438)	1
  (0, 8392)	1
  (0, 1886)	1
  (0, 5456)	1
  (0, 7451)	1
  (0, 6834)	1
  (1, 3425)	1
  (1, 2490)	1
  :	:
  (2557, 8346)	1
  (2557, 5340)	1
  (2557, 8731)	1
  (2557, 5895)	1
  (2557, 3590)	1
  (2557, 6735)	1
  (2557, 1021)	1
  (2557, 5249)	1
  (2558, 5321)	1
  (2558, 6723)	1
  (2558, 968)	1
  (2558, 4144)	1
  (2558, 872)	1
  (2559, 285)	1
  (2559, 5282)	1
  (2559, 6268)	1
  (2559, 5316)	1
  (2559, 7917)	1
  (2559, 3331)	1
  (2559, 5612)	1
  (2559, 6738)	1
  (2559, 8616)	1
  (2559, 7904)	1
  (2559, 1676)	1
  (2559, 5894)	1


In [83]:
dense_matrix = X.todense()
print(dense_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [84]:
print(vectorizer.get_feature_names_out())
print(len(vectorizer.get_feature_names_out()))

['10' '100' '101' ... 'zone' 'ótimo' 'últimos']
8842


In [85]:
print(vectorizer.stop_words_)

{'but', 'this', 'its', 'as', 'to', 'and', 'the', 'is', 'film', 'for', 'it', 'an', 'of', 'that', 'movie', 'with', 'in'}


In [86]:
first_review = test_df['text'].iat[0]
print(first_review)

lovingly photographed in the manner of a golden book sprung to life , stuart little 2 manages sweetness largely without stickiness .


In [87]:
sparse_vector = vectorizer.transform([first_review])
print(sparse_vector)
dense_vector = sparse_vector.todense()
np.set_printoptions(threshold=sys.maxsize)
print(dense_vector)
np.set_printoptions(threshold=False)

  (0, 953)	1
  (0, 4442)	1
  (0, 4553)	1
  (0, 4613)	1
  (0, 4679)	1
  (0, 4770)	1
  (0, 4783)	1
  (0, 5754)	1
  (0, 7537)	1
  (0, 7705)	1
  (0, 8720)	1
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [88]:
vectorizer = CountVectorizer(max_df=300)
X = vectorizer.fit_transform(train_df["text"])
print(vectorizer.stop_words_)

{'but', 'this', 'its', 'as', 'to', 'and', 'the', 'is', 'film', 'for', 'it', 'an', 'of', 'that', 'movie', 'with', 'in'}


In [89]:
vectorizer = CountVectorizer(stop_words=['the', 'this', 'these', 'in', 'at', 'for'])
X = vectorizer.fit_transform(train_df["text"])

In [90]:
vectorizer = CountVectorizer(max_df=300)
(train_df, test_df) = load_train_test_dataset_pd()
X = vectorizer.fit_transform(train_df["text"])
vectorize = lambda x: vectorizer.transform([x]).toarray()[0]
(X_train, X_test, y_train, y_test) = create_train_test_data(train_df, test_df, vectorize)
clf = train_classifier(X_train, y_train)
test_classifier(test_df, clf)

Found cached dataset rotten_tomatoes (/home/zhenya/.cache/huggingface/datasets/rotten_tomatoes/default/1.0.0/40d411e45a6ce3484deed7cc15b82a53dad9a72aafd9f86f8f227134bec5ca46)
Found cached dataset rotten_tomatoes (/home/zhenya/.cache/huggingface/datasets/rotten_tomatoes/default/1.0.0/40d411e45a6ce3484deed7cc15b82a53dad9a72aafd9f86f8f227134bec5ca46)


              precision    recall  f1-score   support

           0       0.74      0.69      0.72       160
           1       0.71      0.76      0.74       160

    accuracy                           0.73       320
   macro avg       0.73      0.73      0.73       320
weighted avg       0.73      0.73      0.73       320

